#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""legacy_makefile_stub.py

Generate stub ``Makefile`` files in legacy tree-style codebases so the
``project_topology`` overlay can produce ``BuildDescriptor`` /
``ProjectModule`` facts for each directory.

Why this exists
---------------
Legacy codebases (C, Pro*C, COBOL, shell, INI, JP1) often organise
source files into a deep folder hierarchy with no ``Makefile`` at the
root of each "module" subtree. The ``project_topology`` overlay
relies on the ``parse_make`` analyzer to emit a ``BuildDescriptor``
for every recognised ``Makefile``; without one, ``resolver.py`` has
no descriptor facts to feed into the ``ProjectModule`` graph and the
module becomes invisible to ``get_project_modules``.

The tool walks a directory, classifies each subdirectory by its
source-file signature, and writes the minimum-viable ``Makefile``
stub (single ``all:`` target) that satisfies ``parse_make``.

What this tool does NOT do
--------------------------
* It does **not** look at a specific project. No folder names, no
  business unit codes, no list of subdirectories, no project paths,
  no repository identifiers are baked in. Pointing the tool at any
  legacy tree yields an equivalent result.

* It does **not** parse existing ``Makefile`` content. It only
  checks for file existence among the conventional names
  (``Makefile`` / ``makefile`` / ``GNUmakefile``).

* It does **not** overwrite any pre-existing
  ``Makefile`` / ``makefile`` / ``GNUmakefile``. Use ``--force`` to
  bypass that protection.

* It does **not** import or interact with the graph database / MCP
  / vector store. After stubs are written, the user or follow-up
  tooling runs the standard sync command (e.g.
  ``dev sync code --full-scan`` or
  ``code-tiny/tools/sync/incremental_sync.py --parsers
  project_topology --full-scan``) to ingest the new descriptors.

Example
-------
Dry-run first::

    python code-tiny/scripts/legacy_makefile_stub.py \\
        --root /path/to/legacy/C/source --dry-run

Apply (creates ``<root>/Makefile`` plus one ``Makefile`` per
qualifying subdirectory)::

    python code-tiny/scripts/legacy_makefile_stub.py \\
        --root /path/to/legacy/C/source

Strict mode (Pro*C only, ignore plain-C directories)::

    python code-tiny/scripts/legacy_makefile_stub.py \\
        --root /path/to/legacy/C/source --require-pc
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, List, Optional, Sequence, Set, Tuple


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Conventional build-descriptor file names recognised by project_topology.
MAKEFILE_NAMES: Tuple[str, ...] = ("Makefile", "makefile", "GNUmakefile")

# Source-file extensions used by the eligibility heuristic.
PROC_EXT: str = ".pc"
C_EXT: str = ".c"

# Pre-classification skip list. Combined with the "starts with '.'" rule these
# cover VCS, caches, IDE metadata, harness config, and typical build outputs.
SKIP_DIR_EXACT: Set[str] = {
    # Version control
    ".git", ".svn", ".hg",
    # JavaScript / Node dependencies (shouldn't appear in legacy C trees but
    # listed defensively).
    "node_modules",
    # Tooling caches
    ".cache", ".pytest_cache", ".mypy_cache", ".ruff_cache",
    # Editor / IDE metadata
    "__pycache__", ".idea", ".vscode",
    # Harness configuration (handled separately by sync tooling).
    ".serena", ".cortext-harness",
    # Common build-output directories.
    "target", "build", "dist", "out",
}

# Stub body. Single literal ``all:`` target satisfies the parse_make
# regex ^([A-Za-z0-9_./%+-][^:=\n]*?)\s*:(?![=]). Body is intentionally
# minimal; the real build logic (if any) lives elsewhere.
STUB_MAKEFILE: str = (
    "# AUTO-GENERATED by legacy_makefile_stub.py -- DO NOT EDIT\n"
    "# This stub exists so the project_topology overlay can register a\n"
    "# BuildDescriptor for this directory. The body is intentionally\n"
    "# minimal: real build logic (if any) lives outside Makefiles\n"
    "# (shell scripts, JP1 units, batch handlers, etc.).\n"
    "# Replace this file with a real Makefile to take over.\n"
    "all:\n"
)


# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class EligibilityDecision:
    """Outcome of classifying one directory."""

    path: Path
    pc_count: int
    c_count: int
    eligible: bool
    reason: str  # "pc" | "c-threshold" | "no-source" | "unreadable"


@dataclass
class StubReport:
    """Accumulated outcome of a full walk."""

    written: List[Path] = field(default_factory=list)
    skipped: List[Path] = field(default_factory=list)
    ineligible: List[Tuple[Path, str]] = field(default_factory=list)
    would_write: List[Path] = field(default_factory=list)
    root_makefile: Optional[str] = None  # "wrote" | "skipped-exists" | "would-write" | "not-emitted"


# ---------------------------------------------------------------------------
# Pure helpers (importable for tests)
# ---------------------------------------------------------------------------


def is_skipped_dirname(name: str) -> bool:
    """Return True if a directory with this basename should be skipped entirely."""
    if name in SKIP_DIR_EXACT:
        return True
    # Any hidden directory (leading dot) is treated as tooling/config and
    # never scanned. This automatically covers .git, .cache, .github,
    # .serena, .idea, .vscode, .cortext-harness, .DS_Store parents, ...
    if name.startswith("."):
        return True
    return False


def classify_directory(
    dir_path: Path,
    *,
    min_c_files: int,
    require_pc: bool,
) -> EligibilityDecision:
    """Decide whether ``dir_path`` qualifies for a stub ``Makefile``.

    Detection is purely extension-based:

    * If any direct child file has extension ``.pc`` (Pro*C source) the
      directory is eligible immediately.
    * Otherwise, if ``require_pc`` is False and the directory contains at
      least ``max(1, min_c_files)`` ``.c`` files, it is eligible as a plain
      C project.
    * Otherwise it is ineligible.

    Throwing exceptions on permission errors yields an ``unreadable``
    decision rather than crashing the whole walk.
    """
    pc_count = 0
    c_count = 0
    try:
        iterator = dir_path.iterdir()
    except (PermissionError, FileNotFoundError, NotADirectoryError):
        return EligibilityDecision(dir_path, 0, 0, False, "unreadable")

    for entry in iterator:
        try:
            if not entry.is_file():
                continue
        except OSError:
            continue
        suffix = entry.suffix.lower()
        if suffix == PROC_EXT:
            pc_count += 1
        elif suffix == C_EXT:
            c_count += 1

    if pc_count > 0:
        return EligibilityDecision(dir_path, pc_count, c_count, True, "pc")
    if not require_pc and c_count >= max(1, min_c_files):
        return EligibilityDecision(dir_path, pc_count, c_count, True, "c-threshold")
    return EligibilityDecision(dir_path, pc_count, c_count, False, "no-source")


def walk_subdirs(root: Path, *, max_depth: int = 4) -> Iterable[Path]:
    """Yield non-skipped subdirectories of ``root``, up to ``max_depth`` levels.

    Yielded paths include both the immediate children and their own
    descendants; the caller decides how to use them.
    """
    stack: List[Tuple[Path, int]] = [(root, 0)]
    while stack:
        current, depth = stack.pop()
        if depth > max_depth:
            continue
        try:
            children = list(current.iterdir())
        except (PermissionError, FileNotFoundError, NotADirectoryError):
            continue
        for child in children:
            try:
                if child.is_dir() and not is_skipped_dirname(child.name):
                    yield child
                    stack.append((child, depth + 1))
            except OSError:
                continue


def has_existing_makefile(dir_path: Path) -> bool:
    """Return True if any conventional Makefile name already exists."""
    for name in MAKEFILE_NAMES:
        candidate = dir_path / name
        try:
            if candidate.is_file():
                return True
        except OSError:
            continue
    return False


def write_stub(target: Path, *, dry_run: bool, force: bool) -> str:
    """Write the stub ``Makefile`` at ``target``.

    Returns one of:

    * ``"wrote"``         — file created on disk.
    * ``"would-write"``   — dry-run; nothing was written.
    * ``"skipped-exists"``— a conventional Makefile already exists and
      ``force`` is False; nothing was written.
    """
    if has_existing_makefile(target.parent) and not force:
        return "skipped-exists"
    if dry_run:
        return "would-write"
    target.write_text(STUB_MAKEFILE, encoding="utf-8")
    return "wrote"


def write_root_stub(
    root: Path,
    *,
    dry_run: bool,
    force: bool,
) -> str:
    """Write (or skip) the root ``Makefile`` stub. Independent of subdir eligibility."""
    target = root / "Makefile"
    return write_stub(target, dry_run=dry_run, force=force)


# ---------------------------------------------------------------------------
# Main driver
# ---------------------------------------------------------------------------


def generate_stubs(
    root: Path,
    *,
    min_c_files: int = 3,
    require_pc: bool = False,
    dry_run: bool = False,
    force: bool = False,
    quiet: bool = False,
) -> StubReport:
    """Walk ``root`` and emit stub Makefiles for every eligible subdirectory.

    Returns a ``StubReport`` describing what happened. The caller decides
    whether to print or exit-code on the report.
    """
    report = StubReport()

    subdirs = list(walk_subdirs(root, max_depth=4))
    any_eligible = False

    for sub in subdirs:
        decision = classify_directory(
            sub, min_c_files=min_c_files, require_pc=require_pc
        )
        target = sub / "Makefile"
        if not decision.eligible:
            report.ineligible.append((sub, decision.reason))
            continue
        any_eligible = True
        outcome = write_stub(target, dry_run=dry_run, force=force)
        _record(report, target, outcome)

    if any_eligible:
        root_outcome = write_root_stub(root, dry_run=dry_run, force=force)
        report.root_makefile = root_outcome
    else:
        report.root_makefile = "not-emitted"

    if not quiet:
        _print_summary(report)

    return report


def _record(report: StubReport, target: Path, outcome: str) -> None:
    if outcome == "wrote":
        report.written.append(target)
    elif outcome == "would-write":
        report.would_write.append(target)
    elif outcome == "skipped-exists":
        report.skipped.append(target)


def _print_summary(report: StubReport) -> None:
    print("--- legacy_makefile_stub decision matrix ---")
    for path in report.written:
        print(f"[wrote]       {path}")
    for path in report.would_write:
        print(f"[would-write] {path}")
    for path in report.skipped:
        print(f"[skipped]     {path}")
    for path, reason in report.ineligible:
        print(f"[ineligible]  {path}  ({reason})")
    print("--- summary ---")
    print(f"  written:    {len(report.written)}")
    print(f"  would-write:{len(report.would_write)}")
    print(f"  skipped:    {len(report.skipped)}")
    print(f"  ineligible: {len(report.ineligible)}")
    print(f"  root stub:  {report.root_makefile}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="legacy_makefile_stub",
        description=(
            "Generate stub Makefiles so project_topology can register "
            "BuildDescriptors in legacy tree-style codebases."
        ),
    )
    parser.add_argument(
        "--root",
        required=True,
        help="Project root directory to scan (must exist and be a directory).",
    )
    parser.add_argument(
        "--min-c-files",
        type=int,
        default=3,
        help=(
            "Minimum .c file count to treat a directory as a generic "
            "C project when no .pc files are present. Default: 3."
        ),
    )
    parser.add_argument(
        "--require-pc",
        action="store_true",
        help=(
            "Only emit stubs in directories containing at least one "
            ".pc (Pro*C) file. Disables the .c-count fallback."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Walk and classify only; print actions without writing.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help=(
            "Overwrite a pre-existing Makefile / makefile / GNUmakefile. "
            "Without this flag the tool never overwrites."
        ),
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress per-directory decision lines (summary still printed).",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)

    root = Path(args.root).resolve()
    if not root.exists() or not root.is_dir():
        print(f"error: --root {root!s} is not an existing directory", file=sys.stderr)
        return 1

    report = generate_stubs(
        root,
        min_c_files=args.min_c_files,
        require_pc=args.require_pc,
        dry_run=args.dry_run,
        force=args.force,
        quiet=args.quiet,
    )

    # Exit 2 only when the root stub *was* emitted and at least one eligible
    # subdir was skipped because of an existing Makefile. That signals a
    # partially-bootstrapped state the operator should investigate.
    root_emitted = report.root_makefile in ("wrote", "would-write")
    if root_emitted and report.skipped:
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())


#   1. Apply tool :
#   python code-tiny/scripts/legacy_makefile_stub.py \
#       --root /Users/youracc/yourproject
#   1.  stub Makefiles will be created
#   2. Sync topology overlay:
#   python code-tiny/tools/sync/incremental_sync.py \
#       --root /Users/youracc/yourproject \
#       --project-id sampleproject --project-name sampleproject \
#       --parsers project_topology --full-scan \
#       --falkordb-graph sampleproject
#   3. Verify MCP:
#   mcp__graph_mcp__get_project_modules(
#       project_id="sampleproject",
#       parser_type="android",
#       include_dependencies=True
#   )
