//! Port của `code-tiny/mcp/tool_metadata.py` — shared MCP tool catalog,
//! single source of truth for all backend `list_mcp_functions`.
//!
//! The catalog data itself (43 hand-written entries, byte-exact, including
//! the `parser_type` fan-out input injected at Python module import time) is
//! shipped as `data/catalog.json`, generated byte-for-byte from the Python
//! module by `scripts/rust_mcp/generate_data.py`. The serving logic below is
//! the Rust port of `build_catalog`.
//!
//! Byte-compatibility contract (verified by `tests/catalog_parity.rs`):
//! * entry order preserved (canonical `_FULL_CATALOG` order),
//! * `deepcopy` semantics on override (`item.update(overrides[name])`),
//! * `list_mcp_functions` payload equals the Python contract-layer listing.

use std::sync::OnceLock;

use serde_json::{json, Map, Value};

const CATALOG_JSON: &str = include_str!("../data/catalog.json");
const UNIFIED_JSON: &str = include_str!("../data/unified.json");

struct ToolMetadata {
    full_catalog: Vec<Value>,
    unified: UnifiedMetadata,
}

pub struct UnifiedMetadata {
    pub server_name: String,
    pub server_version: String,
    pub instructions: String,
    pub tool_names: Vec<String>,
    pub parameter_guidelines: Value,
    pub wire_descriptions: Map<String, Value>,
    pub fanout_search_tool_names: std::collections::BTreeSet<String>,
    pub android_overrides: Map<String, Value>,
}

fn metadata() -> &'static ToolMetadata {
    static METADATA: OnceLock<ToolMetadata> = OnceLock::new();
    METADATA.get_or_init(|| {
        let full_catalog: Vec<Value> =
            serde_json::from_str(CATALOG_JSON).expect("catalog.json must be a JSON array");
        let unified_value: Value =
            serde_json::from_str(UNIFIED_JSON).expect("unified.json must be a JSON object");
        let unified_object = unified_value.as_object().expect("unified.json object");
        let wire_descriptions = unified_object
            .get("wire_descriptions")
            .and_then(Value::as_object)
            .cloned()
            .unwrap_or_default();
        let fanout_search_tool_names = unified_object
            .get("fanout_search_tool_names")
            .and_then(Value::as_array)
            .map(|items| {
                items
                    .iter()
                    .filter_map(Value::as_str)
                    .map(str::to_string)
                    .collect()
            })
            .unwrap_or_default();
        let android_overrides = unified_object
            .get("android_overrides")
            .and_then(Value::as_object)
            .cloned()
            .unwrap_or_default();
        ToolMetadata {
            full_catalog,
            unified: UnifiedMetadata {
                server_name: unified_object
                    .get("server_name")
                    .and_then(Value::as_str)
                    .unwrap_or("graph_mcp")
                    .to_string(),
                server_version: unified_object
                    .get("server_version")
                    .and_then(Value::as_str)
                    .unwrap_or("1.2.0")
                    .to_string(),
                instructions: unified_object
                    .get("instructions")
                    .and_then(Value::as_str)
                    .unwrap_or_default()
                    .to_string(),
                tool_names: unified_object
                    .get("tool_names")
                    .and_then(Value::as_array)
                    .map(|items| {
                        items
                            .iter()
                            .filter_map(Value::as_str)
                            .map(str::to_string)
                            .collect()
                    })
                    .unwrap_or_default(),
                parameter_guidelines: unified_object
                    .get("parameter_guidelines")
                    .cloned()
                    .unwrap_or_else(|| json!({})),
                wire_descriptions,
                fanout_search_tool_names,
                android_overrides,
            },
        }
    })
}

/// `_FULL_CATALOG` — full catalog (union of all backends), canonical order.
pub fn full_catalog() -> &'static [Value] {
    &metadata().full_catalog
}

/// Unified server metadata (`data/unified.json`).
pub fn unified() -> &'static UnifiedMetadata {
    &metadata().unified
}

/// `_CATALOG_BY_NAME` — catalog entry by tool name.
pub fn catalog_entry(name: &str) -> Option<&'static Value> {
    full_catalog()
        .iter()
        .find(|entry| entry.get("name").and_then(Value::as_str) == Some(name))
}

/// Catalog `inputs` list for `tool_name`.
pub fn catalog_inputs(name: &str) -> Option<&'static Vec<Value>> {
    catalog_entry(name).and_then(|entry| entry.get("inputs")).and_then(Value::as_array)
}

/// `build_catalog` — return the filtered, optionally-overridden list of tool
/// metadata entries, preserving the canonical ordering.
pub fn build_catalog(
    tool_names: &std::collections::BTreeSet<String>,
    overrides: Option<&Map<String, Value>>,
) -> Vec<Value> {
    let mut result: Vec<Value> = Vec::new();
    let mut seen: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for entry in full_catalog() {
        let Some(name) = entry.get("name").and_then(Value::as_str) else {
            continue;
        };
        if !tool_names.contains(name) || seen.contains(name) {
            continue;
        }
        let mut item = entry.clone();
        if let Some(entry_override) = overrides.and_then(|overrides| overrides.get(name))
            && let Some(entry_override) = entry_override.as_object()
            && let Some(item_object) = item.as_object_mut()
        {
            // Python `item.update(overrides[name])` — replace fields.
            for (key, value) in entry_override {
                item_object.insert(key.clone(), value.clone());
            }
        }
        result.push(item);
        seen.insert(name.to_string());
    }
    result
}

/// `build_catalog(_UNIFIED_TOOL_NAMES)` — the unified server's catalog.
pub fn unified_catalog() -> Vec<Value> {
    let names: std::collections::BTreeSet<String> = unified().tool_names.iter().cloned().collect();
    build_catalog(&names, None)
}

/// `ANDROID_OVERRIDES` — Android backend description/use-case patches.
pub fn android_overrides() -> &'static Map<String, Value> {
    &metadata().unified.android_overrides
}

/// Whether `tool_name` fans out across query engines when `parser_type` is
/// omitted (`FANOUT_SEARCH_TOOL_NAMES`).
pub fn is_fanout_search_tool(name: &str) -> bool {
    metadata().unified.fanout_search_tool_names.contains(name)
}

/// Required parameter names for `tool_name`, in catalog order
/// (`_required_params` from unified_mcp).
pub fn required_params(name: &str) -> Vec<String> {
    let Some(entry) = catalog_entry(name) else {
        return Vec::new();
    };
    entry
        .get("inputs")
        .and_then(Value::as_array)
        .map(|inputs| {
            inputs
                .iter()
                .filter_map(|input| {
                    let object = input.as_object()?;
                    if object.get("required").and_then(Value::as_bool) == Some(true) {
                        object
                            .get("name")
                            .and_then(Value::as_str)
                            .map(|value| value.trim().to_string())
                            .filter(|value| !value.is_empty())
                    } else {
                        None
                    }
                })
                .collect()
        })
        .unwrap_or_default()
}

/// Accepted parameter names for `tool_name`, in catalog order
/// (`_accepted_params` from unified_mcp).
pub fn accepted_params(name: &str) -> Vec<String> {
    let Some(entry) = catalog_entry(name) else {
        return Vec::new();
    };
    entry
        .get("inputs")
        .and_then(Value::as_array)
        .map(|inputs| {
            inputs
                .iter()
                .filter_map(|input| {
                    input
                        .as_object()?
                        .get("name")
                        .and_then(Value::as_str)
                        .map(|value| value.trim().to_string())
                        .filter(|value| !value.is_empty())
                })
                .collect()
        })
        .unwrap_or_default()
}

/// Catalog `example` for `tool_name`.
pub fn catalog_example(name: &str) -> Option<&'static Value> {
    catalog_entry(name).and_then(|entry| entry.get("example"))
}

/// The wire description a tool carries on `tools/list`: unified-registered
/// tools use their `@mcp_server.tool(description=...)`, proxied tools use the
/// catalog description.
pub fn wire_description(name: &str) -> Option<String> {
    if let Some(description) = unified().wire_descriptions.get(name) {
        return description.as_str().map(str::to_string);
    }
    catalog_entry(name)
        .and_then(|entry| entry.get("description"))
        .and_then(Value::as_str)
        .map(str::to_string)
}

/// `list_mcp_functions` payload (unified server contract): the served catalog
/// plus parameter guidelines. Matches the Python contract-layer listing
/// (`build_catalog(_UNIFIED_TOOL_NAMES)`).
pub fn list_mcp_functions_payload() -> Value {
    let functions = unified_catalog();
    json!({
        "total_count": functions.len(),
        "parameter_guidelines": unified().parameter_guidelines,
        "functions": functions,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_data_loads() {
        assert_eq!(full_catalog().len(), 43);
        assert_eq!(unified().tool_names.len(), 39);
    }

    #[test]
    fn build_catalog_filters_and_preserves_order() {
        let names: std::collections::BTreeSet<String> =
            ["search_functions", "list_parsers", "nonexistent"]
                .into_iter()
                .map(str::to_string)
                .collect();
        let catalog = build_catalog(&names, None);
        let names: Vec<&str> = catalog
            .iter()
            .filter_map(|entry| entry.get("name").and_then(Value::as_str))
            .collect();
        assert_eq!(names, vec!["search_functions", "list_parsers"]);
    }

    #[test]
    fn required_params_match_catalog() {
        assert_eq!(required_params("get_symbol"), vec!["node_id".to_string()]);
        assert_eq!(required_params("find_paths"), vec!["start_function_id".to_string(), "end_function_id".to_string()]);
        assert!(required_params("list_parsers").is_empty());
        // Fan-out injection appended `parser_type` last for search tools.
        let accepted = accepted_params("search_functions");
        assert_eq!(accepted.last().map(String::as_str), Some("parser_type"));
    }

    #[test]
    fn wire_description_prefers_unified_registration() {
        // get_project_modules is registered directly on the unified server
        // with its own description, which differs from the catalog.
        let wire = wire_description("get_project_modules").unwrap();
        assert_eq!(
            wire,
            "Return canonical project modules, descriptors, and dependencies."
        );
        // annotate_node is proxied → catalog description wins.
        let wire = wire_description("annotate_node").unwrap();
        assert_eq!(
            wire,
            "Add or update annotations (notes/tags/severity) on a node for documentation/review purposes."
        );
    }

    #[test]
    fn fanout_tools_declared() {
        assert!(is_fanout_search_tool("search_functions"));
        assert!(!is_fanout_search_tool("explore_graph"));
    }
}
