//! Phase-06 component-gate fixture harness.
//!
//! Every expectation here was generated by the REAL Python reference
//! (`scripts/rust_parity/gen_vector_plane_fixtures.py`, importing
//! `tools.common.primary_vector_sync` / `message_scan`) — this is the
//! component evidence the spike NO-GO demanded for the three hazards cosine
//! gates "might not catch" (uuid5 join order, 3-tier redaction, `_hash_vector`)
//! plus the G4 filter/config byte shapes.
//!
//! Lives in `#[cfg(test)]` so the binary keeps its dependency surface; the
//! fixtures are committed under `tests/fixtures/`.

use serde_json::{Map, Value, json};

use crate::hash_vector::hash_vector;
use crate::vector_sync;

fn fixture(name: &str) -> Value {
    let path = format!(
        "{}/tests/fixtures/{name}",
        env!("CARGO_MANIFEST_DIR"),
        name = name
    );
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("missing fixture {path}: {error}"));
    serde_json::from_str(&text).unwrap_or_else(|error| panic!("bad fixture {name}: {error}"))
}

fn rows(value: &Value) -> Vec<Map<String, Value>> {
    value
        .as_array()
        .expect("rows array")
        .iter()
        .map(|row| row.as_object().expect("row object").clone())
        .collect()
}

// ── G1 ──────────────────────────────────────────────────────────────────────
#[test]
fn g1_point_id_fixture_parity() {
    let payload = fixture("phase06_g1_point_ids.json");
    let cases = payload["cases"].as_array().expect("cases");
    let mut ids = 0usize;
    for case in cases {
        let input = case["input"].as_array().expect("input");
        let [parser, project_id, symbol_id, root_scope] = [
            input[0].as_str().unwrap(),
            input[1].as_str().unwrap(),
            input[2].as_str().unwrap(),
            input[3].as_str().unwrap(),
        ];
        let result = vector_sync::deterministic_point_id(parser, project_id, symbol_id, root_scope);
        if case["expect_error"].as_bool().unwrap_or(false) {
            assert!(result.is_err(), "expected error for {case:?}");
        } else {
            assert_eq!(
                result.expect("python produced an id for this case"),
                case["id"].as_str().unwrap(),
                "id mismatch for {case:?}"
            );
            ids += 1;
        }
    }
    assert!(ids >= 10, "expected ≥10 id cases, got {ids}");
}

// ── G2 ──────────────────────────────────────────────────────────────────────
#[test]
fn g2_redaction_fixture_parity() {
    let payload = fixture("phase06_g2_redaction.json");
    let cases = payload["cases"].as_array().expect("cases");
    for case in cases {
        assert_eq!(
            vector_sync::redact_text(&case["input"].clone()),
            case["redacted"].as_str().unwrap(),
            "redaction mismatch for input {:?}",
            case["input"]
        );
    }
    let bounded = payload["bounded"].as_array().expect("bounded");
    for case in bounded {
        let parts: Vec<Value> = case["input"].as_array().expect("parts").clone();
        let max_chars = usize::try_from(case["max_chars"].as_i64().expect("max_chars")).expect("positive");
        let result = vector_sync::bounded_text(&parts, max_chars).expect("python produced text");
        assert_eq!(result, case["output"].as_str().unwrap(), "bounded mismatch {case:?}");
    }
}

// ── G3 ──────────────────────────────────────────────────────────────────────
#[test]
fn g3_hash_vector_fixture_parity() {
    let payload = fixture("phase06_g3_hash_vector.json");
    let cases = payload["cases"].as_array().expect("cases");
    for case in cases {
        let size = usize::try_from(case["size"].as_i64().expect("size")).expect("positive size");
        let expected: Vec<f64> = case["vector"]
            .as_array()
            .expect("vector")
            .iter()
            .map(|v| v.as_f64().expect("float"))
            .collect();
        let actual = hash_vector(case["text"].as_str().expect("text"), size).expect("python succeeded");
        assert_eq!(actual.len(), expected.len());
        if let Some((index, (want, got))) = expected
            .iter()
            .zip(actual.iter())
            .enumerate()
            .find(|(_, (want, got))| want.to_bits() != got.to_bits())
        {
            panic!(
                "G3 bit-exactness violated text={:?} size={size} idx={index} want_bits={:x} got_bits={:x}",
                case["text"],
                want.to_bits(),
                got.to_bits(),
            );
        }
    }
}

// ── G4 ──────────────────────────────────────────────────────────────────────
#[test]
fn g4_stale_filter_fixture_parity() {
    let payload = fixture("phase06_g4_stale_filters.json");
    for case in payload["cases"].as_array().expect("cases") {
        let scenario = &case["scenario"];
        let paths: Vec<String> = scenario["paths"]
            .as_array()
            .expect("paths")
            .iter()
            .map(|p| p.as_str().expect("path str").to_string())
            .collect();
        let keep: Vec<String> = scenario["keep"]
            .as_array()
            .expect("keep")
            .iter()
            .map(|p| p.as_str().expect("keep str").to_string())
            .collect();
        let produced = vector_sync::stale_filter(
            scenario.get("parser").and_then(Value::as_str).unwrap_or("go"),
            "P rój",
            "/root",
            &paths,
            &keep,
            scenario["full_replace"].as_bool().expect("full_replace"),
        );
        let calls = case["calls"].as_array().expect("calls");
        let actual_filter = match produced {
            Some(filter) => json!({ "filter": filter }),
            None => {
                assert!(calls.is_empty(), "rust early-out but python called: {case:?}");
                return_call_shape(calls);
                continue;
            }
        };
        assert_eq!(calls.len(), 1, "python made exactly one delete call: {case:?}");
        let expected = &calls[0]["filter"];
        assert_eq!(&actual_filter["filter"], expected, "G4 filter mismatch {case:?}");
        return_call_shape(calls);
    }
}

fn return_call_shape(_calls: &[Value]) {}

#[test]
fn g4_collection_bodies_parity() {
    let payload = fixture("phase06_g4_collection_bodies.json");
    let cases = payload["cases"].as_array().expect("cases");
    let find = |needle: &str| -> &Value {
        cases
            .iter()
            .find(|case| case["case"].as_str().is_some_and(|name| name.starts_with(needle)))
            .unwrap_or_else(|| panic!("missing fixture case {needle}"))
    };
    // Create body: Python VectorParams(size, COSINE) with zero tuning kwargs
    // (default env) — the exact sibling the Rust remote store sends.
    let create = find("create fresh")["calls"].as_array().expect("calls");
    assert_eq!(create.len(), 1);
    assert_eq!(create[0]["vectors_config"], json!({"size": 1024, "distance": "Cosine"}));
    assert_eq!(create[0]["kwargs"], json!({}));
    // Scope index order (tuple order is the call order).
    let indexed: Vec<&str> = find("scope index order")["calls"]
        .as_array()
        .expect("calls")
        .iter()
        .map(|call| call["field"].as_str().expect("field"))
        .collect();
    assert_eq!(indexed, vector_sync::SCOPE_INDEX_FIELDS.to_vec());
    // Size-drift message: the reference raises this exact text; Rust must be
    // byte-identical (produced by the real vector_store::size_drift_message).
    let drift = find("size drift")["calls"].as_str().expect("drift error");
    let mut sizes = std::collections::BTreeMap::new();
    sizes.insert("default".to_string(), 1024_i64);
    let rust_message =
        crate::vector_store::size_drift_message("c", &sizes, 512);
    assert_eq!(rust_message, drift, "drift error text diverged");
    // Exists-and-same-size must produce NO create call.
    assert_eq!(find("exists, same size")["calls"].as_array().expect("calls").len(), 0);
}

// ── G5 inputs (contract e2e: rows → documents) ─────────────────────────────
#[test]
fn g5_documents_fixture_parity() {
    let payload = fixture("phase06_g5_documents.json");
    assert_eq!(payload["scope_mismatch_true"].as_bool(), Some(true));
    for case in payload["cases"].as_array().expect("cases") {
        let mut categories = Vec::new();
        for pair in case["input_categories"].as_array().expect("pairs") {
            let name = pair[0].as_str().expect("category name").to_string();
            categories.push((name, rows(&pair[1])));
        }
        let max_chars = usize::try_from(case["max_chars"].as_i64().expect("max")).expect("positive");
        let result = vector_sync::documents_from_categories(
            &categories,
            case["parser"].as_str().expect("parser"),
            case["root_scope"].as_str().expect("root_scope"),
            max_chars,
        );
        if case["expect_error"].as_bool().unwrap_or(false) {
            let error = result.expect_err("python raised");
            assert_eq!(error, case["error"].as_str().expect("error text"));
            continue;
        }
        let documents = result.expect("python built documents");
        let expected = case["documents"].as_array().expect("documents");
        assert_eq!(documents.len(), expected.len(), "document count");
        for (document, want) in documents.iter().zip(expected.iter()) {
            assert_eq!(document.id, want["id"].as_str().unwrap());
            assert_eq!(document.text, want["text"].as_str().unwrap());
            assert_eq!(
                Value::Object(document.payload.clone()),
                want["payload"],
                "payload mismatch for id={}",
                document.id
            );
        }
    }
}

// ── G4 shape pin: serde sort order == Python insertion order ────────────────
#[test]
fn g4_filter_byte_shape_sorted_equals_python_insertion() {
    let filter = vector_sync::stale_filter(
        "go",
        "p",
        "/r",
        &["a.go".to_string()],
        &["k".to_string()],
        false,
    )
    .expect("filter");
    // Python json.dumps (insertion order) vs serde (sorted) must coincide for
    // every key pair here: must < must_not, key < match.
    assert_eq!(
        serde_json::to_string(&filter).expect("serialize"),
        r#"{"must":[{"key":"project_id_normalized","match":{"value":"p"}},{"key":"parser","match":{"value":"go"}},{"key":"root_scope","match":{"value":"/r"}},{"key":"file_path","match":{"any":["a.go"]}}],"must_not":[{"has_id":["k"]}]}"#
    );
}
